### ISSUE TITLE
How to install and run this in Ubuntu 16.04 Xenial (Linux Mint KDE 18.3)?

### ISSUE THREAD

**Issue by phd21** [lehklu/Vallpaper#1]
Hi  lehklu,

Thanks for doing this for all KDE users.

How to install and run this in Ubuntu 16.04 Xenial (Linux Mint KDE 18.3)?

This looks great, but I cannot run it without getting a "QtQuick 2.7 not installed" error? 

Regards,
Phil (phd21)

**Comment by claydoh** [comment]
This is specifically for Plasmashell, so it does not work on different desktops

**Comment by lehklu** [comment]
You can find more info on the 'product' page: [Vallpaper](https://www.opendesktop.org/p/1197828/)
Requirements would be:
```
KDE Plasma Version: 5.13.2
KDE Frameworks Version: 5.47.0
Qt Version: 5.11.1
```
or better
