### ISSUE TITLE
No add/edit buttons for picture sources.

### ISSUE THREAD

**Issue by KottV** [lehklu/Vallpaper#2]
Hi,

Since 2.0 release in config dialog buttons for /add/edit/remove picture sources is absent.

Vallpaper 2.0 :
![image](https://user-images.githubusercontent.com/4686351/64828579-6e4cf680-d60c-11e9-993f-8e1da186e40c.png)

Vallpaper 1.14 

![image](https://user-images.githubusercontent.com/4686351/64828698-ec110200-d60c-11e9-91e0-4be34f45f3cd.png)

**Comment by lehklu** [comment]
Try to make the window larger, they should be there at the bottom.

**Comment by KottV** [comment]
That works :)
And in 2.0.1 issue is solved, thank you.
